### ISSUE TITLE
Render tokens in source order

### ISSUE THREAD

**Issue by caseycallow** [salesforce-ux/theo#118]
Currently, generated tokens are streamed randomly into source files. Would be nice to have the output file of variables reflect the same source order they were imported in.

**Comment by aputinski** [comment]
Can you give me an example of:
  - current order of your tokens
  - current output
  - expected output?

**Comment by caseycallow** [comment]
Current import order:
```imports:
  - './font-size.yml'
  - './line-height.yml'
  - './font-weight.yml'
  - './spacing.yml'
  - './border.yml'
  - './text-color.yml'
  - './background-color.yml'
  - './gradient.yml'
  - './radius.yml'
  - './duration.yml'
```
Current output:

```
  // Color for paragraphs on light backgrounds
  $text-color-paragraph: #0F2B3D;
  
  $color-silver-light: #96A0AA;
  
  $gradient-cerulean-teal: linear-gradient(to bottom right, #02B3E4, #02CCBA);
  
  $gradient-cerulean-purple: linear-gradient(to bottom right, #02B3E4, #A951ED);
  
  $color-slate-lighter: #B4B9BD;
  
  $color-purple-neue-lightest: #F9F8FD;
  
  $spacing-inline-md: 0 1.5rem 0 0;
  
  $color-magenta-lightest: #FFF8FA;
  
  $base-duration: 0.3s;
  
  $font-size-09: 0.5625rem;
  // Secondary heading color for H6 on light backgrounds
  $text-color-heading-weak: #657482;
...
```
Expected output:
```
$font-size-09: 0.5625rem;
$font-size-12: 0.75rem;
$font-size-13: 0.8125rem;
$font-size-14: 0.875rem;
$font-size-16: 1rem;
$font-size-18: 1.125rem;
$font-size-24: 1.5rem;
$font-size-28: 1.75rem;
$font-size-32: 2rem;
$font-size-40: 2.5rem;
$font-size-48: 3rem;
$line-height-09: 0.75rem;
$line-height-12: 1.5rem;
$line-height-13: 1.5rem;
$line-height-14: 1.5rem;
$line-height-16: 1.75rem;
$line-height-18: 2rem;
$line-height-24: 2.25rem;
$line-height-28: 2.25rem;
$line-height-32: 2.25rem;
$line-height-40: 3rem;
$line-height-48: 3.75rem;
...

**Comment by aputinski** [comment]
I just published `6.0.0-beta.5`. Let me know if that works better!

**Comment by caseycallow** [comment]
Awesome thank you! The import groupings are now in order but the tokens themselves are still shuffled. Any way to get these to render in order?

Current output:
```
$font-size-40: 2.5rem;
$font-size-32: 2rem;
$font-size-12: 0.75rem;
$font-size-13: 0.8125rem;
$font-size-24: 1.5rem;
$font-size-14: 0.875rem;
$font-size-48: 3rem;
$font-size-16: 1rem;
$font-size-28: 1.75rem;
$font-size-18: 1.125rem;
$font-size-09: 0.5625rem;

```
Expected:
```
$font-size-09: 0.5625rem;
$font-size-12: 0.75rem;
$font-size-13: 0.8125rem;
$font-size-14: 0.875rem;
$font-size-16: 1rem;
$font-size-18: 1.125rem;
$font-size-24: 1.5rem;
$font-size-28: 1.75rem;
$font-size-32: 2rem;
$font-size-40: 2.5rem;
$font-size-48: 3rem;

**Comment by shaunbent** [comment]
+1 for this, would be great for Tokens to be output in the order they're listed.

**Comment by jenniesyip** [comment]
In addition to the ordering, is it possible to have the tokens render without the extraneous line breaks and trailing spaces as well? 

Current Output:
![image](https://user-images.githubusercontent.com/1864971/29841903-033aceb2-8cbc-11e7-822e-f6edcab24cfa.png)

Expected Output:
![image](https://user-images.githubusercontent.com/1864971/29841887-f89d1e42-8cbb-11e7-9330-8cd36766ebfb.png)

**Comment by aputinski** [comment]
Can I get some more info:
 - Operating system
 - Node version

**Comment by aputinski** [comment]
Also, would be helpful to have a minimal token src folder to test.

**Comment by caseycallow** [comment]
I'm on Sierra 10.12.6, and Node v8.3.0. Common JS and scss formats are the only ones that seem to be affected by the extraneous spacing issue of the formats I'm currently rendering (JSON, iOS, android, common JS, scss). Let me know if you need more info!

`src/aliases/font-size.yml`:
```
aliases:
  FONT_SIZE_09: '0.5625rem'
  FONT_SIZE_12: '0.75rem'
  FONT_SIZE_13: '0.8125rem'
  FONT_SIZE_14: '0.875rem'
  FONT_SIZE_16: '1rem'
  FONT_SIZE_18: '1.125rem'
  FONT_SIZE_24: '1.5rem'
  FONT_SIZE_28: '1.75rem'
  FONT_SIZE_32: '2rem'
  FONT_SIZE_40: '2.5rem'
  FONT_SIZE_48: '3rem'
```
`src/font-size.yml`:
```
global:
  type: size
  category: font-size
imports:
  - './aliases/font-size.yml'
props:
  FONT_SIZE_09:
    value: '{!FONT_SIZE_09}'
  FONT_SIZE_12:
    value: '{!FONT_SIZE_12}'
  FONT_SIZE_13:
    value: '{!FONT_SIZE_13}'
  FONT_SIZE_14:
    value: '{!FONT_SIZE_14}'
    comment: 'comment placeholder'
  FONT_SIZE_16:
    value: '{!FONT_SIZE_16}'
  FONT_SIZE_18:
    value: '{!FONT_SIZE_18}'
  FONT_SIZE_24:
    value: '{!FONT_SIZE_24}'
  FONT_SIZE_28:
    value: '{!FONT_SIZE_28}'
  FONT_SIZE_32:
    value: '{!FONT_SIZE_32}'
  FONT_SIZE_40:
    value: '{!FONT_SIZE_40}'
  FONT_SIZE_48:
    value: '{!FONT_SIZE_48}'
```
`src/all.yml`:
```
imports:
  - './font-size.yml'
```

`dist/all.scss`:
```

  
  $font-size-40: 2.5rem;
  
  $font-size-32: 2rem;
  
  $font-size-12: 0.75rem;
  
  $font-size-13: 0.8125rem;
  
  $font-size-24: 1.5rem;
  // comment placeholder
  $font-size-14: 0.875rem;
  
  $font-size-48: 3rem;
  
  $font-size-16: 1rem;
  
  $font-size-28: 1.75rem;
  
  $font-size-18: 1.125rem;
  
  $font-size-09: 0.5625rem;
```

`dist/all.common.js`:
```

module.exports = {
    
    fontSize40: "2.5rem",
    
    fontSize32: "2rem",
    
    fontSize12: "0.75rem",
    
    fontSize13: "0.8125rem",
    
    fontSize24: "1.5rem",
    // comment placeholder
    fontSize14: "0.875rem",
    
    fontSize48: "3rem",
    
    fontSize16: "1rem",
    
    fontSize28: "1.75rem",
    
    fontSize18: "1.125rem",
    
    fontSize09: "0.5625rem",
};
```

`dist/all.json` (no extraneous spacing):
```
{
  "FONT_SIZE_40": "2.5rem",
  "FONT_SIZE_32": "2rem",
  "FONT_SIZE_12": "0.75rem",
  "FONT_SIZE_13": "0.8125rem",
  "FONT_SIZE_24": "1.5rem",
  "FONT_SIZE_14": "0.875rem",
  "FONT_SIZE_48": "3rem",
  "FONT_SIZE_16": "1rem",
  "FONT_SIZE_28": "1.75rem",
  "FONT_SIZE_18": "1.125rem",
  "FONT_SIZE_09": "0.5625rem"
}
```
