### ISSUE TITLE
multi-line strings lad to SyntaxError

### ISSUE THREAD

**Issue by iilei** [salesforce-ux/theo#139]
Hi,

when I just tried to implement a custom html renderer with markdown support in the comments I came across the following:

Valid yaml with markdown inside:
```yaml
# design-tokens/app.yaml
props:
  COLOR_BRAND:
    value: "{!CASPER}"
    type: color
    category: background-color
    comment: >
      folded

       * bullet
       * list
```

Output:
```js
// common.js
module.exports = {
  // folded line
next line
 * bullet

 * list
 * line

last line

  colorBrand: "rgb(159, 170, 181)",
};
```

Which produces a Syntax Error.

I am aware it might seem like a contrived scenario. However, if you would accept a PR I would happily contribute.

Opinions?
