### ISSUE TITLE
Allow for top-level file comments

### ISSUE THREAD

**Issue by bradryanbice** [salesforce-ux/theo#147]
A file generated by Theo can't have documentation comments (as far as I know.)

Maybe institute a comments key in the global area, like so?

```
global:
  category: 'web'
  type: 'color'
  comments: 'This would be a commented out line that would appear at the top of the file.'
```
