### ISSUE TITLE
Issue with accessing meta values?

### ISSUE THREAD

**Issue by bradryanbice** [salesforce-ux/theo#166]
I have this YAML (portion)

```
props:
  # Spacing & Padding
  SDS_ACCORDION_CONTENT_PADDING:
    value: '{!SIZE_MEDIUM}'
    meta:
      css: 'padding'
  SDS_ACCORDION_HEADER_PADDING:
    value: '0 {!SIZE_MEDIUM}'
    meta:
      css: 'padding'
      modifier: 'header'
```

And I'm creating a custom format using this:

```
theo.registerFormat('sdsw.json', `
// Source: {{stem meta.file}}
{
    "props": {
        {{#each props as |prop|}}
        "{{prop.name}}": {
            "value": "{{prop.value}}",
            "meta": {
                "css": "{{prop.meta.css}}",
                "modifier": "{{prop.meta.modifier}}"
            }
        },
        {{/each}}
    }
}
`)
```

Which is returning empty values for the meta (name and value are returning just fine. Is this something I'm doing wrong?
