### ISSUE TITLE
Z-index `-99999` generates `-999991500`

### ISSUE THREAD

**Issue by chris-dura** [salesforce-ux/theo#190]
```yaml
global:
  type: z-index
  category: z-index
  cssProperties:
    - z-index

props:
  - Z_INDEX_DEEPDIVE:
    name: 'my-z-index-deepdive'
    value: '-99999'
```
Output:
```xml
<property name="MY_Z_INDEX_DEEPDIVE" category="z-index">-999991500</property>
```
```scss
$my-z-index-deepdive: -999991500;
```
