### ISSUE TITLE
Inconsistency in variable names scss <-> stylus <-> less

### ISSUE THREAD

**Issue by phun-ky** [salesforce-ux/theo#191]
With this task:

```javascript
const generateColorVariablesForWeb = done => {
  const tasks = targets.map(target => () =>
    gulp
      .src('./src/dt/color-variables.yml')
      .pipe(
        gulpTheo({
          transform: {
            type: 'web'
          },
          format: {
            type: target
          }
        })
      )
      .pipe(rename(`color-variables.${target === 'stylusObj' ? 'styl' : target}`))
      .pipe(gulp.dest('src'))
  );
  return gulp.series(...tasks, seriesDone => {
    seriesDone();
    done();
  })();
};
```

And this DT:

```yaml
props:
  - darkBlue:
    value: '{!bracingBlue}'
    hex: '#004080'
    name: 'color-darkBlue-primary'
    versionName: 'darkBlue'
aliases:
  bracingBlue:
    value: rgb(0, 64, 128)
global:
  type: color
  category: primary

```

I get different casing on the variable names:

in `color-variables.scss`:

```scss
$color-dark-blue-primary: rgb(0, 64, 128);
```

in `color-variables.styl`:

```stylus
$color-darkBlue-primary = rgb(0, 64, 128)
```

in `color-variables.less`:

```less
@color-dark-blue-primary: rgb(0, 64, 128);
```
What gives?
