### ISSUE TITLE
Comments not visible in .scss output

### ISSUE THREAD

**Issue by siiron** [salesforce-ux/theo#58]
@jina mentioned in one of her [talks](https://vimeo.com/181329002#t=1850s), the possibility to have comments in the tokens-file. Currently I'm using .yml as my input, and .scss as my output.

Input:
```yml
---
  global:
    type: "color"
    category: "text-color"
    cssProperties: "color"
  props:
    foo:
      value: "#bada55"
      comment: "A badass color"
    bar:
      value: "#dac0de"
      comment: "Only for the nerds"
    baz:
      value: "#c00ffe"
      comment: "That's a wierd coffee"
```

Output:
```scss
$foo: rgb(186, 218, 85);
$bar: rgb(218, 192, 222);
$baz: rgb(192, 15, 254);
```

I was kinda expecting something like this:
```scss
// A badass color
$foo: rgb(186, 218, 85);
// Only for the nerds
$bar: rgb(218, 192, 222);
// That's a wierd coffee
$baz: rgb(192, 15, 254);
```

But if I change the output to either raw.json or ios.json, I get the key/value for "comment":
```js
{
  "aliases": {},
  "props": {
    "foo": {
      "type": "color",
      "category": "text-color",
      "cssProperties": "color",
      "value": "#bada55",
      "comment": "A badass color",
      "name": "foo"
    },
    ...
    ...
  },
  "propKeys": [
    "foo",
    "bar",
    "baz"
  ]
}
```
Still, I'd love to have them available in .scss as well.

My gulp-task looks like this:

```js
gulp.task('tokens-web', function() {
    return gulp.src('path/to/tokens/*.yml')
        .pipe(theo.plugins.transform('web'))
        .pipe(theo.plugins.format('scss'))
        .pipe(rename({
            prefix: '_'
        }))
        .pipe(gulp.dest('path/to/output'));
});
```

Nothing fancy going on there, except I'm using rename to add an '_' since I'd like the rendered output to be a scss-partial.

Is this not supported, or am I missing something?
